
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1212
 */
public class Menu extends javax.swing.JFrame {
    String host,userName,password;
    Connection con;
    Statement stmt;
    String sqlStatement;
    ResultSet rs;
    String a,b;
        int c,d,e;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        try{
             host="jdbc:mysql://localhost:3306/freshqo";
             userName="root";
             password="carbon12";
            con=DriverManager.getConnection(host,userName,password);
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            sqlStatement="Select * from ORDERS";
            rs=stmt.executeQuery(sqlStatement);
            rs.last();
        }
          catch(SQLException e){
            System.out.println(e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox31 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jCheckBox31.setText("jCheckBox31");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(102, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("PT Serif", 3, 36)); // NOI18N
        jLabel1.setText("MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 26, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox1.setText("CHICKEN MANCHURIAN");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox2.setText("CHICKEN LOLLIPOP");
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 46, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox3.setText("FISH CURRY");
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 85, -1, -1));

        jCheckBox4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox4.setText("BASIL CHICKEN");
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 124, -1, -1));

        jCheckBox5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox5.setText("BAKED PRAWNS");
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 163, -1, -1));

        jCheckBox6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox6.setText("SALAMI SANDWICH");
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 202, -1, -1));

        jCheckBox7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox7.setText("STEAMED RICE");
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 7, -1, -1));

        jCheckBox8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox8.setText("HAKKA NOODLES");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 46, -1, -1));

        jCheckBox9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox9.setText("THAI CURRY");
        jPanel1.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 85, -1, -1));

        jCheckBox10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox10.setText("ARRIABATA PASTA");
        jPanel1.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 124, -1, -1));

        jCheckBox11.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox11.setText("VEG DIMSUMS");
        jPanel1.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 163, -1, -1));

        jCheckBox12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox12.setText("VEG MANCHURIAN");
        jPanel1.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jCheckBox13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox13.setText("JAIN MIXED VEG");
        jPanel1.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 7, -1, -1));

        jCheckBox14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox14.setText("DHOKLA");
        jPanel1.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 46, -1, -1));

        jCheckBox15.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox15.setText("DAL MAKHNI");
        jPanel1.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 85, -1, -1));

        jCheckBox16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox16.setText("BANANA CHIPS");
        jPanel1.add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 124, -1, -1));

        jCheckBox17.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox17.setText("VEG PULAO");
        jPanel1.add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 163, -1, -1));

        jCheckBox18.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox18.setText("SALAD");
        jPanel1.add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 202, -1, -1));

        jCheckBox19.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox19.setText("VEG ROLL");
        jPanel1.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 7, -1, -1));

        jCheckBox20.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox20.setText("CHICKEN ROLL");
        jPanel1.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 46, -1, -1));

        jCheckBox21.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox21.setText("MALAI CHAP");
        jPanel1.add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 85, -1, -1));

        jCheckBox22.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox22.setText("CHICKEN BIRYANI");
        jPanel1.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 124, -1, -1));

        jCheckBox24.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox24.setText("RAITA");
        jPanel1.add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 202, -1, -1));

        jCheckBox23.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jCheckBox23.setText("BUTTER CHICKEN");
        jCheckBox23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox23ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 163, -1, -1));

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -320, 760, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 720, -1));

        jRadioButton2.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jRadioButton2.setText("ANB");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 78, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jRadioButton3.setText("19th Hole");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 78, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton1.setText("SELECT QUANTITY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 180, 40));

        jRadioButton1.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jRadioButton1.setText("CND");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 78, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/aryangupta/Desktop/11.jpeg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, 740, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);
        jCheckBox6.setEnabled(true);
        jCheckBox7.setEnabled(true);
        jCheckBox8.setEnabled(true);
        jCheckBox9.setEnabled(true);
        jCheckBox10.setEnabled(true);
        jCheckBox11.setEnabled(true);
        jCheckBox12.setEnabled(true);
        jCheckBox13.setEnabled(true);
        jCheckBox14.setEnabled(true);
        jCheckBox15.setEnabled(true);
        jCheckBox16.setEnabled(true);
        jCheckBox17.setEnabled(true);
        jCheckBox18.setEnabled(true);
        jCheckBox19.setEnabled(true);
        jCheckBox20.setEnabled(true);
        jCheckBox21.setEnabled(true);
        jCheckBox22.setEnabled(true);
        jCheckBox23.setEnabled(true);
        jCheckBox24.setEnabled(true);
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jCheckBox4.setEnabled(false);
        jCheckBox5.setEnabled(false);
        jCheckBox6.setEnabled(false);
        jCheckBox8.setEnabled(false);
        jCheckBox9.setEnabled(false);
        jCheckBox10.setEnabled(false);
        jCheckBox11.setEnabled(false);
        jCheckBox12.setEnabled(false);
        jCheckBox23.setEnabled(false);
        jCheckBox19.setEnabled(false);
        jCheckBox20.setEnabled(false);
        jCheckBox21.setEnabled(false);
        jCheckBox22.setEnabled(false);
        
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
           jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);
        jCheckBox6.setEnabled(true);
        jCheckBox7.setEnabled(true);
        jCheckBox8.setEnabled(true);
        jCheckBox9.setEnabled(true);
        jCheckBox10.setEnabled(true);
        jCheckBox11.setEnabled(true);
        jCheckBox12.setEnabled(true);
        jCheckBox13.setEnabled(true);
        jCheckBox14.setEnabled(true);
        jCheckBox15.setEnabled(true);
        jCheckBox16.setEnabled(true);
        jCheckBox17.setEnabled(true);
        jCheckBox18.setEnabled(true);
        jCheckBox19.setEnabled(true);
        jCheckBox20.setEnabled(true);
        jCheckBox21.setEnabled(true);
        jCheckBox22.setEnabled(true);
        jCheckBox23.setEnabled(true);
        jCheckBox24.setEnabled(true);
        jCheckBox7.setEnabled(false);
        jCheckBox8.setEnabled(false);
        jCheckBox9.setEnabled(false);
        jCheckBox10.setEnabled(false);
        jCheckBox11.setEnabled(false);
        jCheckBox12.setEnabled(false);
        jCheckBox13.setEnabled(false);
        jCheckBox14.setEnabled(false);
        jCheckBox15.setEnabled(false);
        jCheckBox16.setEnabled(false);
        jCheckBox18.setEnabled(false);
        jCheckBox19.setEnabled(false);
        jCheckBox21.setEnabled(false);
        jCheckBox17.setEnabled(false);
        jCheckBox24.setEnabled(false);
        
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
          jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);
        jCheckBox6.setEnabled(true);
        jCheckBox7.setEnabled(true);
        jCheckBox8.setEnabled(true);
        jCheckBox9.setEnabled(true);
        jCheckBox10.setEnabled(true);
        jCheckBox11.setEnabled(true);
        jCheckBox12.setEnabled(true);
        jCheckBox13.setEnabled(true);
        jCheckBox14.setEnabled(true);
        jCheckBox15.setEnabled(true);
        jCheckBox16.setEnabled(true);
        jCheckBox17.setEnabled(true);
        jCheckBox18.setEnabled(true);
        jCheckBox19.setEnabled(true);
        jCheckBox20.setEnabled(true);
        jCheckBox21.setEnabled(true);
        jCheckBox22.setEnabled(true);
        jCheckBox23.setEnabled(true);
        jCheckBox24.setEnabled(true);
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jCheckBox4.setEnabled(false);
        jCheckBox5.setEnabled(false);
        jCheckBox6.setEnabled(false);
        jCheckBox20.setEnabled(false);
        jCheckBox22.setEnabled(false);
        jCheckBox23.setEnabled(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jCheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox23ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        d=0;
        b="";
        a="";
        if(jCheckBox1.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE CHICKEN MANCHURIAN");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"CHICKEN MANCHURIAN"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox2.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE CHICKEN LOLLIPOP");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"CHICKEN LOLLIPOP"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox3.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE FISH CURRY");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"FISH CURRY"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox4.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE BASIL CHICKEN");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"BASIL CHICKEN"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox5.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE BAKED PRAWNS");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"BAKED PRAWNS"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox6.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE SALAMI SANDWICH");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"SALAMI SANDWICH"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox7.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE STEAMED RICE");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"STEAMED RICE"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox8.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE HAKKA NOODLES");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"HAKKA NOODLES"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox9.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE THAI CURRY");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"THAI CURRY"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox10.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE ARIABATTA PASTA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"ARIABATTA PASTA"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox11.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE VEG DIMSUMS");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"VEG DIMSUMS"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox12.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"VEG MANCHURIAN"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox13.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"JAIN MIXED VEG"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox14.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"DHOKLA"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox15.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"DAL MAKHNI"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox16.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"BANANA CHIPS"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox17.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"VEG PULAO"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox18.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE SALAD");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"SALAD"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox19.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE VEG ROLL");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"VEG ROLL"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox20.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE CHICKEN ROLL");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"CHICKEN ROLL"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox21.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE MALAI CHAP");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"MALAI CHAP"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox22.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE CHICKEN BIRYANI");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"CHICKEN BIRYANI"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox23.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE BUTTER CHICKEN");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"BUTTER CHCIKEN"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox24.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"RAITA"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;

        }
        try
        {
            e=rs.getInt("ORDERNO");
            e=e+1;
            sqlStatement="insert into orders values("+e+",'"+b+"',"+d+")";
            stmt.executeUpdate(sqlStatement);
            EndPage second= new EndPage();
            second.setVisible(true);
        }
        catch(SQLException x){
            System.out.println(x.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
